---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-web-service
spec:
  selector:
    app: dvwa-web
    tier: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80